{
 "title": "Dash",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Host memory",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job='node',instance='exporter:9100'} - node_memory_MemFree_bytes{job='node',instance='exporter:9100'} - node_memory_Buffers_bytes{job='node',instance='exporter:9100'} - node_memory_Cached_bytes{job='node',instance='exporter:9100'}",
     "legendFormat": "Used"
    },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free" }
   ]
  },
  {
   "title": "Host disk IO Utilization",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{job='node',instance='exporter:9100',device!~'^(md\\\\d+$|dm-)'}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Memory usage per container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{name!~\"\"}) by (image)",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "Network I/O per container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\"}[1m])) by (image)",
     "legendFormat": "IN {{image}}"
    },
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{image!=\"\"}[1m])) by (image)",
     "legendFormat": "OUT {{image}}"
    }
   ]
  },
  {
   "title": "CPU Usage per container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\"}[1m])) by (image)",
     "legendFormat": "{{image}}"
    }
   ]
  }
 ]
}