{
 "title": "Dash",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Network I/O per container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\"}[1m])) by (image)",
     "legendFormat": "IN {{image}}"
    },
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{image!=\"\"}[1m])) by (image)",
     "legendFormat": "OUT {{image}}"
    }
   ]
  },
  {
   "title": "Memory usage per container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{name!~\"\"}) by (image)",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "CPU Usage per container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\"}[1m])) by (image)",
     "legendFormat": "{{image}}"
    }
   ]
  }
 ]
}